export const SocialEvents = {
  FRIEND_REQUEST_SENT: 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUEST_DECLINED: 'FRIEND_REQUEST_DECLINED',
  /** См. @app/contracts/kafka/social — подписка в ленте (feed_sources) */
  FRIEND_ADDED: 'FRIEND_ADDED',
  FRIEND_REMOVED: 'FRIEND_REMOVED',

  COMMUNITY_CREATED: 'COMMUNITY_CREATED',
  COMMUNITY_UPDATED: 'COMMUNITY_UPDATED',
  COMMUNITY_DELETED: 'COMMUNITY_DELETED',
  COMMUNITY_SUBSCRIBED: 'COMMUNITY_SUBSCRIBED',
  COMMUNITY_UNSUBSCRIBED: 'COMMUNITY_UNSUBSCRIBED',
} as const;

export type SocialEventType = (typeof SocialEvents)[keyof typeof SocialEvents];

