CREATE DATABASE auth;
CREATE DATABASE profile;
CREATE DATABASE content;
CREATE DATABASE feed;
CREATE DATABASE social;
CREATE DATABASE media;

GRANT ALL PRIVILEGES ON DATABASE auth TO app;
GRANT ALL PRIVILEGES ON DATABASE profile TO app;
GRANT ALL PRIVILEGES ON DATABASE content TO app;
GRANT ALL PRIVILEGES ON DATABASE feed TO app;
GRANT ALL PRIVILEGES ON DATABASE social TO app;
GRANT ALL PRIVILEGES ON DATABASE media TO app;